version: '3.10'

services:
  db:
    image: postgres:14.7
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    env_file:
      - config/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    build:
      context: .
    restart: always
    volumes:
      - .:/code
      - static:/static
    ports:
      - 8000:8000
    depends_on:
      - db

  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  postgres_data:
  static:
